Document window messaging under webapp
Chainlit/docs pull request #194
Opened 2024-11-14 14:34 UTC by jfperusse-bhvr

Documentation for the window messaging feature.

Source: https://github.com/Chainlit/chainlit/pull/1469
Cookbook: https://github.com/Chainlit/cookbook/pull/154

2024-11-19 14:32 UTC, dokterbob requested changes
Thanks, the contents of the docs really look great!

However, I was wondering: perhaps there's a better place for it.

What I imagine is some kind of guide (what you have here), in it's own section in 'Advanced Features'. In addition, I reckon' that the API Reference should be updated with the new calls.

Lastly, I would suggest you add a link to where the cookbook entry will be, from the guide.

Thanks so much, this is really great work!

2024-11-19 14:39 UTC, jfperusse-bhvr commented
Thanks @dokterbob ! The reason I put it under Web App is based on the equivalent feature for the Copilot integration, as documented under https://docs.chainlit.io/deploy/copilot. The window messaging is similar, but for the Web App instead. Let me know what you think.

I'll see where this can be added in the API reference. From what I can tell, CopilotFunction is not currently documented in the API reference.

2024-12-10 08:46 UTC, willydouhard approved these changes

2025-01-03 12:57 UTC, willydouhard approved these changes

2025-01-03 12:57 UTC, merged